### ISSUE TITLE
Can you support Visual Studio 2019 or later?

### ISSUE THREAD

**Issue by BenjaminGu** [RedNicStone/CubiCAD#1]
When I tried to generate a Visual Studio 2019 project file with CMake, the errors and the warnings are as follows.
And I attached CMake log files.

```
CMake Error at cmake/CompilerWarnings.cmake:71 (list):
  list does not recognize sub-command PROJECT_WARNINGS
Call Stack (most recent call first):
  CMakeLists.txt:59 (set_project_warnings)
```

```
CMake Warning (dev) at lib/shaderc/CMakeLists.txt:16 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```

```
CMake Warning (dev) at lib/shaderc/libshaderc_util/CMakeLists.txt:15 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```

```
CMake Warning (dev) at lib/shaderc/libshaderc/CMakeLists.txt:15 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```

[CMakeOutput.log](https://github.com/RedNicStone/CubiCAD/files/8192822/CMakeOutput.log)
[CMakeError.log](https://github.com/RedNicStone/CubiCAD/files/8192823/CMakeError.log)

**Comment by RedNicStone** [comment]
Hi! Thanks for your interest in the project!
CMake's warnings are standard when building in debug mode. You can use `-Wno-dev` to suppress them.
The error seems the be a result of the msvc environment. I will look into it.
Could you also elaborate on how you are using Visual Studio? I was under the impression it did not run under linux.

**Comment by BenjaminGu** [comment]
Hello, thanks for the reply.
I tried to compile CubiCAD in Windows 10.
Is there any reason your engine doesn't support Windows?

**Comment by RedNicStone** [comment]
Thanks for the quick reply, I was not aware that you were using the Windows platform.
Currently only Linux support is planned. 
Making CubiCAD Windows compatible would probably not be a difficult task, the only Linux specific code is anything that touches the file system (Dos uses '\' instead of '/' I believe). Perhaps some changes would also have to be made to the CMake files.
However, this is not possible for me as I have no way of testing CubiCAD on Windows or, well, on any other platform than Linux. 
However I would be more than happy to accept any pull requests regarding windows support!

**Comment by RedNicStone** [comment]
Closed due to inactivity
